source /usr/local/Cellar/cabal-install/1.24.0.2_2/etc/bash_completion.d/cabal
source /usr/local/Cellar/flow/0.37.4/etc/bash_completion.d/flow-completion.bash
source /usr/local/Cellar/git/2.11.0/etc/bash_completion.d/git-completion.bash
source /usr/local/Cellar/git/2.11.0/etc/bash_completion.d/git-prompt.sh
source /usr/local/Cellar/hub/2.2.9/etc/bash_completion.d/hub.bash_completion.sh
source /usr/local/Cellar/leiningen/2.7.1/etc/bash_completion.d/lein-completion.bash
source /usr/local/Cellar/mercurial/4.0.1/etc/bash_completion.d/hg-completion.bash
source /usr/local/Cellar/node/7.3.0/etc/bash_completion.d/npm
source /usr/local/Cellar/node5/5.12.0/etc/bash_completion.d/npm
source /usr/local/Cellar/nvm/0.32.1/etc/bash_completion.d/nvm
source /usr/local/Cellar/opam/1.2.2_2/etc/bash_completion.d/opam_completion.sh
source /usr/local/Cellar/pass/1.6.5_1/etc/bash_completion.d/password-store
source /usr/local/Cellar/task/2.5.1/etc/bash_completion.d/task.sh
source /usr/local/Cellar/the_silver_searcher/0.33.0/etc/bash_completion.d/ag.bashcomp.sh
source /usr/local/Cellar/tig/2.2.1/etc/bash_completion.d/tig-completion.bash
source /usr/local/Cellar/tmux/2.3_2/etc/bash_completion.d/tmux
source /usr/local/Cellar/unar/1.10.1/etc/bash_completion.d/lsar.bash_completion
source /usr/local/Cellar/unar/1.10.1/etc/bash_completion.d/unar.bash_completion
